name: 🔄️ CI

on:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    name: 🔍 Lint
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🛠️ Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile --filter=.

      - name: 🔍 Lint
        run: |
          bun run tsc
          bun run lint

  test:
    name: 🧪 Tests
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🛠️ Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🧪 Run tests
        run: bun run test
