name: 🔄️ CI
on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  lint:
    name: 🔍 Lint
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - name: Install dependencies
        run: bun install --frozen-lockfile --filter=.

      - name: Lint
        run: |
          bun run tsc
          bun run lint

  test:
    name: 🧪 Tests
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - name: Install dependencies
        run: bun install --filter=tests

      - name: Run tests
        run: bun run test
