name: Update Starter Root Dev Dependencies

on:
  schedule:
    # Run at 2:00 AM UTC (before most developers start coding globally)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Update starter root dev dependencies
        run: pnpm update-create-bunup-starter-root-dev-dependencies

      - name: Build packages
        run: pnpm build

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Git user
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "chore: update starter root dev dependencies"

      - name: Release
        if: steps.check_changes.outputs.changes == 'true'
        run: pnpm release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
